contact/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.contact, name='contact'),
]

flight_academy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('vouchers/', include('flights.urls')),
    path('shopping_bag/', include('shopping_bag.urls')),
    path('payments/', include('payments.urls')),
    path('user_profile/', include('user_profile.urls')),
    path('training/', include('training.urls')),
    path('contact/', include('contact.urls')),
    path('newsletter/', include('newsletter.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'flight_academy.views.handler404'
handler500 = 'flight_academy.views.handler500'

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
]

contact/models.py
from django.db import models
from training.models import Training


class Contact(models.Model):
    """ A model to handle a contact form """

    first_name = models.CharField(max_length=75, blank=False, null=False)
    last_name = models.CharField(max_length=75, blank=False, null=False)
    email = models.EmailField(max_length=256, blank=False, null=False)
    phone_num = models.CharField(max_length=30, null=True)
    specific_course = models.ForeignKey(
        Training, on_delete=models.CASCADE, null=False, blank=False)
    message = models.TextField(blank=False, null=False)
    msg_date = models.DateTimeField(auto_now_add=True, blank=False, null=False)

    def __str__(self):
        return self.email

contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = [
            'first_name', 'last_name', 'email', 'phone_num',
            'specific_course', 'message'
        ]

    def __init__(self, *args, **kwargs):
        # https://stackoverflow.com/a/72025478
        super().__init__(*args, **kwargs)

contact/views.py
import datetime
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django.conf import settings
from django.contrib import messages
from .forms import ContactForm
from .models import Contact


def contact(request):
    """ A view to allow a superuser to add a new voucher """
    if request.method == 'POST':
        form = ContactForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            form.save()
            messages.success(
                request,
                "Thank You! A member of our team will be in "
                "touch soon with further information."
            )
            return redirect('home')
        else:
            messages.error(
                request,
                'Failed to submit form. '
                'Please ensure the form is valid.'
            )
    else:
        form = ContactForm()

    template = 'contact/contact.html'
    context = {
            'form': form,
    }

    return render(request, 'contact/contact.html', {'form': form})

contact/templates/contact/contact.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-12 overlay-contact-page">
            <div class="col-12 col-md-10 offset-md-1 col-lg-6 offset-lg-3">
                    <h2 class="contact-h2 mt-3">Register Your Interest In Training</h2>
                    <p>Please enter your details below and a member of our team will be in touch with further information.</p>
                    <form method="POST" action="{% url 'contact' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-navy">Cancel</a>
                        <button class="btn btn-red" type="submit">Submit</button>
                    </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block postloadjs %}
    <script>
        $('#id_phone_num').attr('type', 'tel');
    </script>
{% endblock %}